language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: cursoebuyplace
  api_key:
    secure: b06rQrTe1drmP7cshUmDq+jduIn3eHpMdH9zTWeIQiNyLVQDDOBafFmFjHKVMnAwmav7QaB/sF4NrUSYaSNvPWxZ+KR3ggHYeEdUSzIeMNo7Bao0elKONUfL2+1wV+8GxMeP4UckuCJempz7SKEQmkY6cPt3lptzTPJq4x9ZRtbN1fP4MP4b9nj9iYEsVndyFz/IvZzCaX+U/9vJhGp6bwbW/qMXUxBI3ofBKLXlbczXWSLkhx8tV0P+tTq0ZZ2mVTOPiL8V1a/NsHtK93jZyTfVwTD+upE2CKdI/gR5PVcPlroXbZmzRQMsGEddSr1Cdg69y5+S3Jbfk92bW5ICauZo8YMXAROzEEUVGAH39QjR9ELm0bDpmLzXQgb9SFEWKeYfTSaHgcts10j+tvQ7XG54lA1oj89sVmSG72hJ0/Zj7CumPmbep2TSufhrjBKXbooMqeU/fqVe3rxyiXcN2/7Tm3WNcJgsq43mxItn5BVbNAQ7RY5W2msi3Ekouir1iGE/DPBv15qta1p6ONmKPvXn8YTt0jqlp5yoRdBFjI86BiCgBCZHnfoi7MbuF7u21yLTnDXBabvzeM4/aTY8o3epcB5mJILkNYiRHMYs9LhdJz+b9j9yFylp/E0puXPaD6tfoTb4mnPz8dQqz8NDXaPACwmGFzYTwSsToDjqD+U=
