version:  '3'
services:
 db:
   image: postgres:11
   environment:
     POSTGRES_PASSWORD: 123
     PGDATA: /var/lib/postgresql/data/pgdata
     POSTGRES_USER: root
     POSTGRES_DB: tareasdb
   volumes:
     - ./pgdata3:/var/lib/postgresql/data
   ports:
     - "5433:5432"
 api:
   image: node:16
   restart: always
   environment:
     DBHOST: db
   command: bash -c 'cd /usr/src/app/ && npm start'
   tty: true
   ports:
     - "8080:8080"
   volumes:
     - ./:/usr/src/app/
   depends_on:
     - db
